dubbo:
  protocol: 
   port: 20880
   name: dubbo
  application: 
   name: console-server-app
  registry:
   address: zookeeper://127.0.0.1:2181
   timeout: 30000
  packageName: com.tdh.gps.console.service.impl
  
mongodb:
    address: 127.0.0.1:27017
    username: admin
    password: 123456
    database: test
    authenticationDatabase: test
    connectionsPerHost: 100
    connectTimeout: 60000
    maxWaitTime: 120000
    maxConnectionIdleTime: 600000
    threadsAllowedToBlockForConnectionMultiplier: 50
    socketTimeout: 30000
    minConnectionsPerHost: 10
    
server:
  port: 8888
  session:
   timeout: 300

spring:
    redis:
        host: 127.0.0.1
        password: 
        port: 6379
        timeout: 10000
        pool:
         max-active: 100
         max-idle: 10
         min-idle: 1
         max-wait: 30000

logging:
  level:
    root: info