dubbo:
  protocol:
    port: 20880
    name: dubbo
  application:
    name: console-web-app
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 30000
  packageName: com.tdh.gps.console

server:
  port: 8889 
  session:
   timeout: 300

security:
#  oauth2:
#    client:
#      clientId: my-trusted-client
#      clientSecret: secret
#      userAuthorizationUri: http://localhost:8080/oauth/authorize
#      grant-type: password
      
#      scope: read

#      scope:
#      - read
#      - write
#      - trust
#      access-token-uri: http://localhost:8080/oauth/token
      
#      resource-ids:
#      - console_web_rest_api
#      authorized-grant-types:
#      - password
#      - authorization_code
#      - refresh_token
#      - implicit
#      access-token-validity-seconds: 1800
#      refresh-token-validity-seconds: 3000

#    resource:
#      userInfoUri: http://localhost:8889/console
#    authorization:
#      check-token-access: http://localhost:8080/oauth/check_token
  basic:
    enabled: false
 
sso:
 security:
  oauth2:
   storeType: jwt
  jwt:
   signingKey: awbeci
   
# redis configuration
spring:
  redis: 
    host: 127.0.0.1
    password: 
    port: 6379
    timeout: 10000
    pool:
      max-active: 100
      max-idle: 10
      min-idle: 1
      max-wait: 30000
   