dubbo:
  protocol:
    port: 20880
    name: dubbo
  application:
    name: console-web-app
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 30000
  packageName: com.tdh.gps.console

server:
  port: 8889 

security:
#  oauth2:
#    client:
#      clientId: my-trusted-client
#      clientSecret: secret
#      userAuthorizationUri: http://localhost:8080/oauth/authorize
#      grant-type: password
      
#      scope: read

#      scope:
#      - read
#      - write
#      - trust
#      access-token-uri: http://localhost:8080/oauth/token
      
#      resource-ids:
#      - console_web_rest_api
#      authorized-grant-types:
#      - password
#      - authorization_code
#      - refresh_token
#      - implicit
#      access-token-validity-seconds: 1800
#      refresh-token-validity-seconds: 3000

#    resource:
#      userInfoUri: http://localhost:8889/console
#    authorization:
#      check-token-access: http://localhost:8080/oauth/check_token
  basic:
    enabled: false
 
sso:
 security:
  oauth2:
   storeType: jwt
  jwt:
   signingKey: awbeci
   
spring: 
  profiles:
    active: dev
    #includ中,nacos的配置文件对应 starex-mysql, starex-swagger2
    include: 
  main:
    allow-bean-definition-overriding: true
  application:
    name: console-web
  cloud:
    nacos:
      discovery: 
        # 服务注册地址
        server-addr: localhost:8848
        # 注册命名空间
        namespace: ad67d78d-1978-45c5-9c1b-1acba7229190
        metadata: 
          preserved.heart.beat.interval: 3000
          preserved.heart.beat.timeout: 6000
          preserved.ip.delete.timeout: 6000
      config:
        # 配置中心地址
        server-addr: localhost:8848
        # 服务命名空间
        namespace: ad67d78d-1978-45c5-9c1b-1acba7229190
        # 配置文件格式
        file-extension: yaml
        prefix: console
# redis configuration
  redis:
    database: 0
    host: 127.0.0.1
    password: 
    port: 6379
    timeout: 10000
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 1
        max-wait: 30000
#log configuration   
logging:
  level:
    root: info